package com.pactstudios.games.tafl.core.es.model.log;

import java.util.Date;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.pactstudios.games.tafl.core.consts.Constants;
import com.pactstudios.games.tafl.core.es.model.TaflMatch;
import com.pactstudios.games.tafl.core.es.model.objects.GamePiece;

@DatabaseTable(tableName = Constants.DbConstants.LOG_TABLE)
public class MatchLogEntry {

    public static final String ID_COLUMN = "_id";
    public static final String MATCH_ID_COLUMN = "match_id";
    public static final String PIECE_ID_COLUMN = "piece_id";
    public static final String X1_COLUMN = "x1";
    public static final String Y1_COLUMN = "y1";
    public static final String X2_COLUMN = "x2";
    public static final String Y2_COLUMN = "y2";
    public static final String UPDATED_COLUMN = "updated";

    public static final String[] COLUMN_MAP = new String[] {
        MATCH_ID_COLUMN,
        PIECE_ID_COLUMN,
        X1_COLUMN,
        Y1_COLUMN,
        X2_COLUMN,
        Y2_COLUMN,
        UPDATED_COLUMN,
    };

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int _id;

    @DatabaseField(foreign = true, foreignAutoRefresh = true, columnName = MATCH_ID_COLUMN, canBeNull = false)
    public TaflMatch match;

    @DatabaseField(foreign = true, foreignAutoRefresh = true, columnName = PIECE_ID_COLUMN, canBeNull = false)
    public GamePiece piece;

    @DatabaseField(columnName = X1_COLUMN, canBeNull = false)
    public int x1;

    @DatabaseField(columnName = Y1_COLUMN, canBeNull = false)
    public int y1;

    @DatabaseField(columnName = X2_COLUMN, canBeNull = false)
    public int x2;

    @DatabaseField(columnName = Y2_COLUMN, canBeNull = false)
    public int y2;

    @DatabaseField(columnName = UPDATED_COLUMN, canBeNull = false)
    public Date updated;

    @ForeignCollectionField
    public ForeignCollection<GamePiece> killedPieces;

    @Override
    public int hashCode() {
        return _id;
    }

    @Override
    public boolean equals(Object other) {
        return other != null && other instanceof MatchLogEntry && (other == this || ((MatchLogEntry)other)._id == _id) ;
    }

    @Override
    public String toString() {
        return Integer.toString(_id);
    }
}
