package com.pactstudios.games.tafl.core.es.model.objects;

import java.util.Date;

import com.artemis.Entity;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import com.pactstudios.games.tafl.core.consts.Constants;
import com.pactstudios.games.tafl.core.es.model.TaflMatch;
import com.pactstudios.games.tafl.core.es.model.log.MatchLogEntry;

@DatabaseTable(tableName = Constants.DbConstants.PIECE_TABLE)
public class GamePiece {

    public static final String ID_COLUMN = "_id";
    public static final String MATCH_ID_COLUMN = "match_id";
    public static final String TYPE_COLUMN = "type";
    public static final String KILLED_COLUMN = "killed";
    public static final String X_COLUMN = "x";
    public static final String Y_COLUMN = "y";
    public static final String UPDATED_COLUMN = "updated";

    public static final String[] COLUMN_MAP = new String[] {
        MATCH_ID_COLUMN,
        TYPE_COLUMN,
        KILLED_COLUMN,
        X_COLUMN,
        Y_COLUMN,
        UPDATED_COLUMN,
    };

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int _id;

    @DatabaseField(columnName = TYPE_COLUMN, canBeNull = false)
    public PieceType type;

    public Entity entity;

    @DatabaseField(columnName = X_COLUMN, canBeNull = false)
    public int x;

    @DatabaseField(columnName = Y_COLUMN, canBeNull = false)
    public int y;

    @DatabaseField(columnName = UPDATED_COLUMN, canBeNull = false)
    public Date updated;

    @DatabaseField(foreign = true, foreignAutoRefresh = true, columnName = MATCH_ID_COLUMN, canBeNull = false)
    public TaflMatch match;

    @DatabaseField(foreign = true, foreignAutoRefresh = true, columnName = KILLED_COLUMN, canBeNull = true)
    public MatchLogEntry killed;

    @Override
    public int hashCode() {
        return _id;
    }

    @Override
    public boolean equals(Object other) {
        return other != null && other instanceof GamePiece && (other == this || ((GamePiece)other)._id == _id) ;
    }

    @Override
    public String toString() {
        return Integer.toString(_id);
    }
}
